id: I71B8DB06
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:09:21+00:00'
last_modified: '2022-06-08T11:39:24.919209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30449
  title: བོད་ཀྱི་མཛེས་རིས་སྒྱུ་རྩལ་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A0A3:
      image_group_id: I1PD36341
      title: ''
      total_pages: 208
      order: 1
      base_file: A0A3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
