id: P009526
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30449
  title: བོད་ཀྱི་མཛེས་རིས་སྒྱུ་རྩལ་གཏེར་མཛོད
  author: ''
  volumes:
    390833fda5194de193f9de59ee650e4b:
      image_group_id: I1PD36341
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
